apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: image-definitions-data
  namespace: image-definitions
  labels:
    app.kubernetes.io/name: image-definitions
    app.kubernetes.io/component: storage
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  # Uncomment and modify for specific storage class
  # storageClassName: fast-ssd
